// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Stock.API.Models.DbContexts;

#nullable disable

namespace Stock.API.Migrations
{
    [DbContext(typeof(StockAPIDbContext))]
    [Migration("20231203111917_mig-2")]
    partial class mig2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Stock.API.Models.Stock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("654c2128-776e-4979-8940-b334a554b515"),
                            Count = 10,
                            ProductId = new Guid("12a54947-1543-4473-b7e4-58e2c99a8f90")
                        },
                        new
                        {
                            Id = new Guid("5425173e-fcae-4820-a5a1-c25cf249c14c"),
                            Count = 10,
                            ProductId = new Guid("b23cfb37-a81c-492d-9d99-5c4b68ece80b")
                        },
                        new
                        {
                            Id = new Guid("7e2f2b5a-848b-4d6e-b246-9308d1f69f22"),
                            Count = 10,
                            ProductId = new Guid("74688be0-2c9a-4193-be98-3ea5e906a1f3")
                        },
                        new
                        {
                            Id = new Guid("15aa2d9c-e5f3-441d-be44-d28b5b3db862"),
                            Count = 10,
                            ProductId = new Guid("540dba8c-5970-45a3-ab56-969c26677921")
                        },
                        new
                        {
                            Id = new Guid("15d80b0f-16cc-4ad3-be79-cf367d935764"),
                            Count = 10,
                            ProductId = new Guid("fbf11afa-c125-4fa8-a046-5fe927d792c7")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
